default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password:
  host: localhost
  port: 3306

development:
  <<: *default
  database: good_night_dev

test:
  <<: *default
  database: good_night_test

# TODO: add production config
